version: '3.5'

services:
  app:
    image: rafaelbmateus/go-transactions:latest
    build:
      context: .
      dockerfile: build/Dockerfile
      target: base
    command: go run api/main.go
    ports:
      - "3000:3000"
